### ISSUE TITLE
Failed to load rake

### ISSUE THREAD

**Issue by jcserracampos** [corgibytes/ruby_193_docker#5]
Hello,

I just found this docker image and I'm trying to ruby a Rails 3.2.17 project.

When I execute `bundle exec rake db:setup` I'm getting the following error:

```
root@88190767a97d:/app# bundle exec rake db:setup
bundler: failed to load command: rake (/usr/local/bundle/bin/rake)
SyntaxError: /usr/local/bundle/gems/json-2.3.0/lib/json/common.rb:156: syntax error, unexpected tPOW, expecting ')'
    Parser.new(source, **(opts||{})).parse
                         ^
/usr/local/bundle/gems/json-2.3.0/lib/json/common.rb:156: syntax error, unexpected ')', expecting keyword_end
    Parser.new(source, **(opts||{})).parse
                                    ^
/usr/local/bundle/gems/json-2.3.0/lib/json/common.rb:179: syntax error, unexpected tPOW, expecting ')'
    Parser.new(source, **(opts||{})).parse
                         ^
/usr/local/bundle/gems/json-2.3.0/lib/json/common.rb:179: syntax error, unexpected ')', expecting keyword_end
    Parser.new(source, **(opts||{})).parse
                                    ^
  /usr/local/bundle/gems/json-2.3.0/lib/json.rb:2:in `require'
  /usr/local/bundle/gems/json-2.3.0/lib/json.rb:2:in `<top (required)>'
  /usr/local/bundle/gems/honeybadger-2.7.2/lib/honeybadger/util/http.rb:3:in `require'
  /usr/local/bundle/gems/honeybadger-2.7.2/lib/honeybadger/util/http.rb:3:in `<top (required)>'
  /usr/local/bundle/gems/honeybadger-2.7.2/lib/honeybadger/config.rb:11:in `require'
  /usr/local/bundle/gems/honeybadger-2.7.2/lib/honeybadger/config.rb:11:in `<top (required)>'
  /usr/local/bundle/gems/honeybadger-2.7.2/lib/honeybadger/agent.rb:4:in `require'
  /usr/local/bundle/gems/honeybadger-2.7.2/lib/honeybadger/agent.rb:4:in `<top (required)>'
  /usr/local/bundle/gems/honeybadger-2.7.2/lib/honeybadger.rb:79:in `notify'
  /usr/local/bundle/gems/honeybadger-2.7.2/lib/honeybadger/init/rake.rb:13:in `display_error_message_with_honeybadger'
  /usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:195:in `rescue in standard_exception_handling'
  /usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:186:in `standard_exception_handling'
  /usr/local/bundle/gems/rake-12.2.1/lib/rake/application.rb:80:in `run'
  /usr/local/bundle/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
  /usr/local/bundle/bin/rake:23:in `load'
  /usr/local/bundle/bin/rake:23:in `<top (required)>'
```

**Comment by jcserracampos** [comment]
It was a problem with gem json version.

**Comment by mrbiggred** [comment]
Hi @jcserracampos I am glad you figured out your issue.  I was going to say it appears that your code, or the json gem in this case, is using a Ruby 2.0 feature called double spat:

https://stackoverflow.com/questions/18289152/what-does-a-double-splat-operator-do

Often older gems don't list the Ruby version they are compatible with.  For older applications I often have to manually limit the gem version in the gem file after doing some research and/or trial and error.

I'm also glad you found our Ruby 1.9.3 Docker image useful.  If you have an suggestions for improving the image please let us know.  All the best.

**Comment by jcserracampos** [comment]
I had to fix some versions and it worked like a charm.

I am looking forward to submit PRs or open issues if I find something.

Thank you for your project!
